name: pratica01
description: "A new Flutter project."
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.2.2

  http: ^1.2.1
  # Sua versão do intl mantida conforme solicitado
  intl: ^0.20.2 
  
  # Dependência necessária para o calendário
  table_calendar: ^3.1.2

  cupertino_icons: ^1.0.8

 
# A seção a seguir força o uso de uma versão específica de um pacote.
# Usado aqui para resolver o conflito entre table_calendar e a sua versão do intl.
dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imagens/icone_senhor.png
    - assets/imagens/backgroundSenior.png
    - assets/imagens/logo.png